[0m[[0m[0minfo[0m] [0m[0m[32mConnectionTest:[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[32m- with a single host[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m- test connection *** FAILED ***[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.InvalidQueryException: unconfigured table schema_keyspaces))[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:240)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:86)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1455)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at com.datastax.driver.core.Cluster.init(Cluster.java:158)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:329)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at com.datastax.driver.core.Cluster.connectAsync(Cluster.java:304)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at com.datastax.driver.core.Cluster.connect(Cluster.java:246)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at Helper$.createSessionAndInitKeyspace(Helper.scala:12)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at ConnectionTest.$anonfun$new$2(ConnectionTest.scala:18)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)[0m[0m
[0m[[0m[0minfo[0m] [0m[0m[31m  ...[0m[0m
